version: "3.9"
services:
  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_DB: "service-POSTGRES_DB"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "i871bbbda!"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"